services:
  doorman:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: doorman-app
    env_file:
      - .env
    ports:
      - "2222:2222"
    volumes:
      - ./logs:/logs
    depends_on:
      postgres:
        condition: service_healthy
    # restart: unless-stopped
    # healthcheck:
    #   test:
    #     [
    #       "CMD",
    #       "wget",
    #       "--no-verbose",
    #       "--tries=1",
    #       "--spider",
    #       "http://localhost:2222/health",
    #     ]
    #   interval: 30s
    #   timeout: 3s
    #   retries: 3
    #   start_period: 10s
    networks:
      - doorman-network

  postgres:
    image: postgres:16-alpine
    container_name: doorman-postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U doorman_user -d doorman_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - doorman-network

volumes:
  postgres_data:

networks:
  doorman-network:
    driver: bridge
